### ISSUE TITLE
missing slash in MEQ paths?

### ISSUE THREAD

**Issue by benediamond** [mkoeppe/LiDIA#3]
When I try to directly instantiate an `meq_prime` and use it to build modular polynomials in X, I get read errors:

```cpp
#include <LiDIA/bigint.h>
#include <LiDIA/Fp_polynomial.h>
#include <LiDIA/meq_prime.h>
#include <LiDIA/bigmod.h>

using namespace std;
using namespace LiDIA;

int main(int argc, const char * argv[]) {
  meq_prime meq;
  cout << "success? " << meq.set_prime((unsigned long) 7) << endl;

  bigmod::set_modulus(bigint(7));
  bigmod c;
  c.assign(4);
  Fp_polynomial f;
  f.set_modulus(bigint(7));
  meq.build_poly_in_Y(f, c);
  cout << f << endl;
}
```
yields:
```cpp
success? 0
libc++abi.dylib: terminating with uncaught exception of type LiDIA::generic_error: ropen_meq_file::can't open meq file for l = 7
Abort trap: 6
```
A bit of digging demonstrated that in `meq_prime.h`, the `get_filename_vector(std::vector<std::string>& fn_vec)` routine was missing a slash in its filename, yielding a path like `/usr/local/share/lidia/MOD_EQmeq7`. In fact, changing line 48 to:

```cpp
#define MEQ_PREFIX "/meq"         // prefix for name of data files
```
yields:
```cpp
success? 1
3*x + 5 mod 7
```
see also this permalink:
https://github.com/mkoeppe/LiDIA/blob/f10edd172f858b46caf8efb45c79a742cc2407f1/src/ec_order/include/LiDIA/meq_prime.h#L48

Changing this didn't disrupt any of the tests, as demonstrated in `make check`. I'm on MacOS Mojave.

This fix is of course fairly kludgy; I think the first question is, why does this issue _not_ happen when `meq_prime.cc` is called indirectly by `eco_prime.cc`?

**Comment by mkoeppe** [comment]
Fixed in 21da898aabf84a7ca9787da0ef1142a227d8ded8.
