### ISSUE TITLE
extend eco_prime to F_q?

### ISSUE THREAD

**Issue by benediamond** [mkoeppe/LiDIA#5]
Thanks for your great work. I am very interested in extending many of the functions in `eco_prime.h` to arbitrary finite fields F_q. Most importantly, I'd like to extend `compute_divisor_of_division_polynomial` and its auxiliary functions (`coefficient_comparison`, `compute_coefficients_of_weierstrass_p`, etc.) to the prime-power case. Would there be any interest in this project on your part? I would be willing to contribute significantly, and have already made some progress. Thank you.

**Comment by mkoeppe** [comment]
See issue #6 - there are no active developers.

**Comment by benediamond** [comment]
I have gone ahead and done this: see [benediamond::f_q_support](https://github.com/benediamond/LiDIA/tree/f_q_support).

**Comment by benediamond** [comment]
I've rebased my work to ensure clean diffs; you can now see it at [my master branch](https://github.com/benediamond/LiDIA). You can test it using `examples/ec_order/eco_appl`.

I don't suppose you have any interest in merging this in?

There may be a few bug fixes which are separate from the F_q business; I will go ahead and tag you in them.

**Comment by mkoeppe** [comment]
Thanks for doing that; this makes it easier to share bugfixes. 

I don't plan to merge new features in my branch. If you have bug fixes that you'd like me to merge, it's probably best if you prepare pull requests for those; but no pressure! (I will probably not have the time to cherry-pick from the tagged code.)
